package com.studentos.feature.intelligence.presentation.viewmodel

import androidx.lifecycle.SavedStateHandle
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.studentos.feature.intelligence.domain.model.DailyBrief
import com.studentos.feature.intelligence.domain.model.RecommendationCard
import com.studentos.feature.intelligence.domain.usecase.GenerateDailyBriefUseCase
import com.studentos.feature.intelligence.domain.usecase.GetDailyBriefUseCase
import com.studentos.feature.intelligence.presentation.state.DailyBriefUiState
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import kotlinx.serialization.json.Json
import java.time.Clock
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import javax.inject.Inject

@HiltViewModel
class DailyBriefViewModel @Inject constructor(
    private val getDailyBriefUseCase: GetDailyBriefUseCase,
    private val generateDailyBriefUseCase: GenerateDailyBriefUseCase,
    private val clock: Clock,
    savedStateHandle: SavedStateHandle
) : ViewModel() {

    private val json = Json { ignoreUnknownKeys = true }
    private val dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd")
    private var hasAutoGenerated = false

    private val targetDateParam: String? = savedStateHandle.get<String>("date")

    private val _uiState = MutableStateFlow(DailyBriefUiState())
    val uiState: StateFlow<DailyBriefUiState> = _uiState.asStateFlow()

    init {
        loadBrief(targetDateParam)
    }

    fun loadBrief(date: String? = targetDateParam) {
        val today = LocalDate.now(clock).format(dateFormatter)
        val selectedDate = date ?: today
        _uiState.update { it.copy(isLoading = true, errorMessage = null, todayDate = selectedDate) }

        viewModelScope.launch {
            getDailyBriefUseCase(selectedDate)
                .catch { error ->
                    _uiState.update {
                        it.copy(
                            isLoading = false,
                            errorMessage = error.localizedMessage ?: "Failed to load daily brief"
                        )
                    }
                }
                .collect { brief ->
                    if (brief == null) {
                        // Automatic Generation check: if looking for today's brief and not auto-generated yet
                        if (selectedDate == today && !hasAutoGenerated) {
                            hasAutoGenerated = true
                            generateTodayBrief()
                        } else {
                            _uiState.update {
                                it.copy(
                                    isLoading = false,
                                    isEmpty = true,
                                    dailyBrief = null,
                                    recommendations = emptyList()
                                )
                            }
                        }
                    } else {
                        val cards = parseRecommendations(brief.briefJson)
                        _uiState.update {
                            it.copy(
                                isLoading = false,
                                isEmpty = false,
                                dailyBrief = brief,
                                recommendations = cards,
                                errorMessage = null
                            )
                        }
                    }
                }
        }
    }

    fun loadTodayBrief() {
        loadBrief(null)
    }

    fun generateTodayBrief() {
        val today = _uiState.value.todayDate.ifEmpty {
            LocalDate.now(clock).format(dateFormatter)
        }

        _uiState.update { it.copy(isGenerating = true, errorMessage = null) }

        viewModelScope.launch {
            try {
                val brief = generateDailyBriefUseCase(today)
                val cards = parseRecommendations(brief.briefJson)
                _uiState.update {
                    it.copy(
                        isGenerating = false,
                        isLoading = false,
                        isEmpty = false,
                        dailyBrief = brief,
                        recommendations = cards,
                        errorMessage = null
                    )
                }
            } catch (e: Exception) {
                _uiState.update {
                    it.copy(
                        isGenerating = false,
                        isLoading = false,
                        errorMessage = e.localizedMessage ?: "Generation failed"
                    )
                }
            }
        }
    }

    private fun parseRecommendations(jsonString: String): List<RecommendationCard> {
        return try {
            json.decodeFromString(jsonString)
        } catch (_: Exception) {
            emptyList()
        }
    }
}
