package com.studentos.feature.intelligence.presentation.viewmodel

import androidx.lifecycle.SavedStateHandle
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.studentos.core.intelligence.snapshot.IntelligenceSnapshot
import com.studentos.feature.intelligence.domain.model.DailyBrief
import com.studentos.feature.intelligence.domain.model.RecommendationCard
import com.studentos.feature.intelligence.domain.repository.DailyBriefRepository
import com.studentos.feature.intelligence.orchestrator.IntelligenceOrchestrator
import com.studentos.feature.intelligence.presentation.state.DailyBriefUiState
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import kotlinx.serialization.json.Json
import java.time.Clock
import java.time.Instant
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import javax.inject.Inject

@HiltViewModel
class DailyBriefViewModel @Inject constructor(
    private val repository: DailyBriefRepository,
    private val orchestrator: IntelligenceOrchestrator,
    private val clock: Clock,
    savedStateHandle: SavedStateHandle
) : ViewModel() {

    private val json = Json { ignoreUnknownKeys = true; isLenient = true }
    private val dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd")
    private val timeFormatter = DateTimeFormatter.ofPattern("hh:mm a").withZone(clock.zone)
    private var hasAutoGenerated = false

    private val targetDateParam: String? = savedStateHandle.get<String>("date")

    private val _uiState = MutableStateFlow(DailyBriefUiState())
    val uiState: StateFlow<DailyBriefUiState> = _uiState.asStateFlow()

    init {
        loadBrief(targetDateParam)
    }

    fun loadBrief(date: String? = targetDateParam) {
        val today = LocalDate.now(clock).format(dateFormatter)
        val selectedDate = date ?: today
        _uiState.update { it.copy(isLoading = true, errorMessage = null, todayDate = selectedDate) }

        viewModelScope.launch {
            repository.getBriefForDate(selectedDate)
                .catch { error ->
                    _uiState.update {
                        it.copy(
                            isLoading = false,
                            errorMessage = error.localizedMessage ?: "Failed to load daily brief"
                        )
                    }
                }
                .collect { brief ->
                    if (brief == null) {
                        if (selectedDate == today && !hasAutoGenerated) {
                            hasAutoGenerated = true
                            generateTodayBrief()
                        } else {
                            _uiState.update {
                                it.copy(
                                    isLoading = false,
                                    isGenerating = false,
                                    isEmpty = true,
                                    dailyBrief = null,
                                    recommendations = emptyList(),
                                    attendanceWarnings = emptyList(),
                                    urgentAssignments = emptyList(),
                                    freeSlots = emptyList()
                                )
                            }
                        }
                    } else {
                        updateUiStateWithBrief(brief)
                    }
                }
        }
    }

    fun loadTodayBrief() {
        loadBrief(null)
    }

    fun generateTodayBrief() {
        val todayLocalDate = LocalDate.now(clock)
        val todayStr = todayLocalDate.format(dateFormatter)

        _uiState.update { it.copy(isGenerating = true, errorMessage = null, todayDate = todayStr) }

        viewModelScope.launch {
            try {
                val brief = orchestrator.generateMorningBrief(todayLocalDate)
                updateUiStateWithBrief(brief)
            } catch (e: Exception) {
                _uiState.update {
                    it.copy(
                        isGenerating = false,
                        isLoading = false,
                        errorMessage = e.localizedMessage ?: "Generation failed"
                    )
                }
            }
        }
    }

    private fun updateUiStateWithBrief(brief: DailyBrief) {
        val cards = parseRecommendations(brief.briefJson)
        val snapshot = parseSnapshot(brief.jsonSnapshot)
        val formattedTime = try {
            timeFormatter.format(Instant.ofEpochMilli(brief.guidanceUpdatedAt))
        } catch (_: Exception) {
            ""
        }

        _uiState.update {
            it.copy(
                isLoading = false,
                isGenerating = false,
                isEmpty = false,
                dailyBrief = brief,
                recommendations = cards,
                attendanceWarnings = snapshot?.attendanceWarnings ?: emptyList(),
                urgentAssignments = snapshot?.assignmentsUrgent ?: emptyList(),
                freeSlots = snapshot?.freeSlots ?: emptyList(),
                lastUpdatedFormatted = formattedTime,
                errorMessage = null
            )
        }
    }

    private fun parseRecommendations(jsonString: String): List<RecommendationCard> {
        return try {
            json.decodeFromString(jsonString)
        } catch (_: Exception) {
            emptyList()
        }
    }

    private fun parseSnapshot(jsonString: String): IntelligenceSnapshot? {
        return try {
            json.decodeFromString(jsonString)
        } catch (_: Exception) {
            null
        }
    }
}
